### PR TITLE
Layout Improvements

### PR DESCRIPTION
**Pull request by GitPaulo**
The idea is to make the layout a bit better and more understandable to un-versed users:
- Moved `pomanders` into `knowledge` to not clutter sidebar and I think it makes sense?
- Improved navigation styles, logo, etc.
- Relying more on flexbox here and there
- Minor updates to things (.gitignore, ...)
- Implemented a search functionality (kind of)
  - Requires building an index first with a bash script
  - Only looks through markdown headers at the moment

### Preview
image

### Search Idea
Can be scrapped if you think there's no use for it 🤔 

https://github.com/djcooke/compendium/assets/18451329/c4e1fb63-4b3f-4475-80fd-f9744221c73d

### CODE REVIEW

**Comment by GitPaulo** [comment]
@djcooke let me know if this is something you like and I'll continue. ❤️

**Comment by djcooke** [comment]
Sorry, I'll get to reviewing this on the weekend. In the future, if you make separate PRs for separate features/changes, that would make reviewing simpler and merging cleaner. I appreciate the ideas and enthusiasm though!

**Comment by GitPaulo** [comment]
> Sorry, I'll get to reviewing this on the weekend. In the future, if you make separate PRs for separate features/changes, that would make reviewing simpler and merging cleaner. I appreciate the ideas and enthusiasm though!

No rush, review whenever really! This stuff is mostly me throwing out ideas, feel free to reject stuff. I'll keep things more atomic in the future for sure 👍

**Comment by djcooke** [comment]
I haven't looked through the diff entirely, but initial thoughts:

> Moved pomanders into knowledge to not clutter sidebar and I think it makes sense?

It makes sense, but I'd rather keep it separate so the pages are shorter. It is not a huge menu, so I don't think there's a need to reduce it.

> Improved navigation styles, logo, etc.

* I'm not a fan of the rename from Analysis to Randomness
* I like the idea of having a logo at the top of the menu, but the existing logo is bad and I'd rather not use it anywhere except as a favicon. I am bad at graphics if that is not clear from the site design. 😆
* The menu is broken on mobile/narrow screens
* The "Deep Dungeon" graphic in the menu looks nice, but the whole site is about deep dungeons, so I don't think it makes sense as a heading for the floor pages

> Relying more on flexbox here and there

I haven't looked at this yet, but probably good

> Minor updates to things (.gitignore, ...)

Thank you for adding a helpful readme. It's terrible that I have not done this myself. 😅 

> Implemented a search functionality (kind of)

* This could be very useful. I like it a lot!
* It would be nice to get things like enemy/boss names into it
* I think there's a relative reference to the index somewhere. That's causing the search to only work from root-level pages (broken on floorset pages)

**Comment by GitPaulo** [comment]
@djcooke I tried to implement most of the things you brought up.

> I still kept pomanders in knowledge because with the search and anchors, i don't see a reason to fear long pages? Still can be saved. I just favour small navbars.

LMK what you think 😎

**Review by djcooke — CHANGES_REQUESTED** [review]
* Remove logo on menu
* Leave pomanders in their own section. In addition to reasons already stated, I have plans to further expand the page
* On narrow screens/mobile, the menu can't be closed. Is there a benefit to using flexbox here? It is causing issues. I'm also concerned that other css refactoring will have effects neither you nor I have noticed
* The menu tooltips look awkward. You make a good point that showing the full dungeon names would be better though. I think the ideal improvement would be to remove the extra left margins, increase the menu width a bit as necessary and use the full dungeon names instead of initials
* Would be nice to style the "Floor Guides" heading differently so it's obvious that it's not clickable
* Revert changes on Tips/Strategy page
  * The "General" section wasn't large enough that it needed to be split
  * There's not enough under "Time Management" to have its own section
  * The "especially when playing tank jobs" isn't helpful since every job should be advised to use time efficiently, and healers probably even more so than tanks

**Comment by GitPaulo** [comment]
- [ ] Remove logo on menu
- [ ] Leave pomanders in their own section. In addition to reasons already stated, I have plans to further expand the page
- [ ] On narrow screens/mobile, the menu can't be closed. Is there a benefit to using flexbox here? It is causing issues. I'm also concerned that other css refactoring will have effects neither you nor I have noticed.
- [ ] The menu tooltips look awkward. You make a good point that showing the full dungeon names would be better though. I think the ideal improvement would be to remove the extra left margins, increase the menu width a bit as necessary and use the full dungeon names instead of initials
- [ ] Would be nice to style the "Floor Guides" heading differently so it's obvious that it's not clickable
- [ ] Revert changes on Tips/Strategy page

**Comment by GitPaulo** [comment]
> Is there a benefit to using flexbox here? It is causing issues.

Flexbox is just much easier to use, without breaking (much) stuff, when you've got the setup you have. I'll sort out the issues 👍

> * The menu tooltips look awkward. You make a good point that showing the full dungeon names would be better though. I think the ideal improvement would be to remove the extra left margins, increase the menu width a bit as necessary and use the full dungeon names instead of initials

Tooltips don't really make it any worse and add information to what's there IMO. I'll try the full names.

**Comment by GitPaulo** [comment]
@djcooke I've got a pretty good idea of what you like/don't like. I'll be splitting these changes into small PRs now and going to close this one.

This PR was me just fucking around really. It's a pain for you to review, let's change that.

**Pull request closed without merging**
